<?php
/**
 * MonoTalk - translation system
 */

$translations = [
    'ru' => [
        'nav_home' => 'Главная',
        'nav_create' => 'Создать пост',
        'nav_create_subreddit' => 'Создать сабреддит',
        'nav_profile' => 'Профиль',
        'nav_logout' => 'Выйти',
        'nav_login' => 'Войти',
        'nav_register' => 'Регистрация',
        'nav_news' => 'Новости',
        'nav_settings' => 'Настройки',
        'nav_search_placeholder' => 'Поиск по топикам...',
        'lang_ru' => 'Русский',
        'lang_en' => 'English',
        'sort_hot' => 'Горячее',
        'sort_new' => 'Новые',
        'sort_popular' => 'Популярные',
        'sort_discussed' => 'Обсуждаемые',
        'sidebar_welcome' => 'Добро пожаловать в главное сообщество MonoTalk',
        'sidebar_join' => 'Присоединиться',
        'sidebar_categories' => 'Сабреддиты',
        'sidebar_rules' => 'Правила',
        'sidebar_reset' => 'Сбросить фильтр',
        'rule1' => 'Будьте вежливы и уважайте других',
        'rule2' => 'Не спамьте и не дублируйте контент',
        'rule3' => 'Пишите по теме выбранного сабреддита',
        'rule4' => 'Запрещены оскорбления и травля',
        'btn_all_rules' => 'Все правила сообщества →',
        'post_published' => 'Опубликовано',
        'post_comments' => 'комментариев',
        'post_share' => 'Поделиться',
        'post_save' => 'Сохранить',
        'post_in' => 'в',
        'read_more' => 'Читать далее',
        'empty_posts' => 'Пока нет постов в этой ленте.',
        'btn_create_first' => 'Создать первый пост',
        'like_title' => 'Лайк',
        'search_title' => 'Поиск по топикам',
        'search_placeholder' => 'Поиск по заголовкам и тексту постов...',
        'search_btn' => 'Найти',
        'search_found' => 'Найдено постов',
        'search_no_results' => 'По запросу ничего не найдено.',
        'search_try_other' => 'Попробуйте другие слова или проверьте запрос на опечатки.',
        'create_title' => 'Создать пост',
        'create_title_label' => 'Заголовок',
        'create_category_label' => 'Сабреддит',
        'create_choose_category' => 'Выберите сабреддит',
        'create_subreddit_link' => 'Создать свой сабреддит',
        'create_subreddit_title' => 'Создать сабреддит',
        'create_subreddit_name_label' => 'Название',
        'create_subreddit_desc_label' => 'Описание (необязательно)',
        'create_subreddit_emoji_label' => 'Эмодзи (необязательно)',
        'create_subreddit_submit' => 'Создать',
        'create_content_label' => 'Текст поста',
        'create_placeholder' => 'О чём ваш пост?',
        'create_details' => 'Подробности...',
        'create_format_toolbar' => 'Форматирование текста',
        'create_format_help' => 'Сначала выделите нужную часть текста, а потом нажмите B или I. Форматирование: **жирный** и *курсив*.',
        'create_anonymous' => 'Опубликовать анонимно',
        'create_submit' => 'Опубликовать',
        'welcome_title' => 'Добро пожаловать',
        'welcome_hi' => 'Привет',
        'welcome_text1' => 'Добро пожаловать в MonoTalk. Ты успешно зарегистрировался.',
        'welcome_text2' => 'Здесь ты можешь создавать посты, комментировать и ставить лайки.',
        'welcome_home' => 'На главную',
        'popular_posts' => 'Популярные посты',
        'empty_welcome' => 'Пока нет постов.',
        'create_first' => 'Создай первый!',
        'profile_since' => 'На сайте с',
        'profile_badge' => 'Ваш профиль',
        'profile_edit' => 'Редактировать профиль',
        'profile_edit_title' => 'Редактирование профиля',
        'profile_bio' => 'О себе',
        'profile_bio_placeholder' => 'Расскажите немного о себе',
        'profile_links' => 'Ссылки',
        'profile_website' => 'Личный сайт',
        'profile_github' => 'GitHub',
        'profile_telegram' => 'Telegram',
        'profile_discord' => 'Discord',
        'profile_other_links' => 'Дополнительные ссылки',
        'profile_other_links_hint' => 'По одной ссылке в строке, только http/https.',
        'profile_preview' => 'Превью профиля',
        'profile_preview_empty' => 'Добавьте био или ссылки, чтобы увидеть превью.',
        'profile_bio_counter' => '%d / 300 символов',
        'profile_link_website' => 'сайт',
        'profile_link_other' => 'Ссылка',
        'profile_error_auth' => 'Требуется авторизация',
        'profile_error_avatar' => 'Укажите корректную ссылку на аватар (http/https)',
        'profile_error_website' => 'Сайт должен начинаться с http:// или https://',
        'profile_error_github' => 'GitHub должен начинаться с http:// или https://',
        'profile_error_telegram' => 'Укажите корректный Telegram: ссылка или @username',
        'profile_error_discord' => 'Укажите корректный Discord: ссылка или username',
        'profile_error_other_links' => 'Дополнительные ссылки должны быть в формате http:// или https://',
        'profile_my_posts' => 'Мои посты',
        'profile_user_posts' => 'Посты пользователя',
        'profile_no_posts' => 'Вы ещё не создавали постов.',
        'profile_no_posts_other' => 'Пользователь пока не создавал постов.',
        'profile_avatar_url' => 'Аватар (URL)',
        'profile_avatar_file' => 'Или загрузить файл',
        'profile_save' => 'Сохранить',
        'post_comments_count' => 'комментариев',
        'post_about' => 'О посте',
        'post_author' => 'Автор',
        'post_category' => 'Сабреддит',
        'post_published_at' => 'Опубликовано',
        'post_likes' => 'Лайков',
        'support_title' => 'Поддержите нас!',
        'support_text' => 'Если вам нравится MonoTalk, пожалуйста, поддержите нас!',
        'support_btn' => 'Поддержать',
        'subscribe' => 'Подписаться',
        'unsubscribe' => 'Отписаться',
        'sidebar_subs' => 'Подписки',
        'search' => 'Поиск',
        'user_status_online' => '🟢 В сети',
        'user_status_recent' => '⚫ Был(а) недавно',
        'user_status_minutes_ago' => '⚫ Был(а) %d мин. назад',
        'user_status_hours_ago' => '⚫ Был(а) %d ч. назад',
        'user_status_days_ago' => '⚫ Был(а) %d дн. назад',
        'user_status_weeks_ago' => '⚫ Был(а) %d нед. назад',
        'user_status_months_ago' => '⚫ Был(а) %d мес. назад',
        'user_status_years_ago' => '⚫ Был(а) %d г. назад',
    ],
    'en' => [
        'nav_home' => 'Home',
        'nav_create' => 'Create post',
        'nav_create_subreddit' => 'Create subreddit',
        'nav_profile' => 'Profile',
        'nav_logout' => 'Logout',
        'nav_login' => 'Login',
        'nav_register' => 'Register',
        'nav_news' => 'News',
        'nav_settings' => 'Settings',
        'nav_search_placeholder' => 'Search topics...',
        'lang_ru' => 'Русский',
        'lang_en' => 'English',
        'sort_hot' => 'Hot',
        'sort_new' => 'New',
        'sort_popular' => 'Popular',
        'sort_discussed' => 'Discussed',
        'sidebar_welcome' => 'Welcome to the main MonoTalk community',
        'sidebar_join' => 'Join',
        'sidebar_categories' => 'Subreddits',
        'sidebar_rules' => 'Rules',
        'sidebar_reset' => 'Reset filter',
        'rule1' => 'Be polite and respect others',
        'rule2' => 'No spam or duplicate content',
        'rule3' => 'Stay on topic for the selected subreddit',
        'rule4' => 'No insults or harassment',
        'btn_all_rules' => 'All community rules →',
        'post_published' => 'Published by',
        'post_comments' => 'comments',
        'post_share' => 'Share',
        'post_save' => 'Save',
        'post_in' => 'in',
        'read_more' => 'Read more',
        'empty_posts' => 'No posts in this feed yet.',
        'btn_create_first' => 'Create first post',
        'like_title' => 'Like',
        'search_title' => 'Search topics',
        'search_placeholder' => 'Search by post titles and content...',
        'search_btn' => 'Search',
        'search_found' => 'Posts found',
        'search_no_results' => 'Nothing found for this query.',
        'search_try_other' => 'Try different words or check for typos.',
        'create_title' => 'Create post',
        'create_title_label' => 'Title',
        'create_category_label' => 'Subreddit',
        'create_choose_category' => 'Choose subreddit',
        'create_subreddit_link' => 'Create your subreddit',
        'create_subreddit_title' => 'Create subreddit',
        'create_subreddit_name_label' => 'Name',
        'create_subreddit_desc_label' => 'Description (optional)',
        'create_subreddit_emoji_label' => 'Emoji (optional)',
        'create_subreddit_submit' => 'Create',
        'create_content_label' => 'Post content',
        'create_placeholder' => 'What is your post about?',
        'create_details' => 'Details...',
        'create_format_toolbar' => 'Text formatting',
        'create_format_help' => 'First select the part of the text you want to format, then click B or I. Formatting: **bold** and *italic*.',
        'create_anonymous' => 'Post anonymously',
        'create_submit' => 'Publish',
        'welcome_title' => 'Welcome',
        'welcome_hi' => 'Hi',
        'welcome_text1' => 'Welcome to MonoTalk. You have successfully registered.',
        'welcome_text2' => 'Here you can create posts, comment and like.',
        'welcome_home' => 'Go to home',
        'popular_posts' => 'Popular posts',
        'empty_welcome' => 'No posts yet.',
        'create_first' => 'Create the first one!',
        'profile_since' => 'Member since',
        'profile_badge' => 'Your profile',
        'profile_edit' => 'Edit profile',
        'profile_edit_title' => 'Edit profile',
        'profile_bio' => 'Bio',
        'profile_bio_placeholder' => 'Tell people a bit about yourself',
        'profile_links' => 'Links',
        'profile_website' => 'Website',
        'profile_github' => 'GitHub',
        'profile_telegram' => 'Telegram',
        'profile_discord' => 'Discord',
        'profile_other_links' => 'Other links',
        'profile_other_links_hint' => 'One link per line, http/https only.',
        'profile_preview' => 'Profile preview',
        'profile_preview_empty' => 'Add a bio or links to see the preview.',
        'profile_bio_counter' => '%d / 300 characters',
        'profile_link_website' => 'website',
        'profile_link_other' => 'Link',
        'profile_error_auth' => 'Authorization required',
        'profile_error_avatar' => 'Provide a valid avatar URL (http/https)',
        'profile_error_website' => 'Website must start with http:// or https://',
        'profile_error_github' => 'GitHub must start with http:// or https://',
        'profile_error_telegram' => 'Provide a valid Telegram link or @username',
        'profile_error_discord' => 'Provide a valid Discord link or username',
        'profile_error_other_links' => 'Other links must use http:// or https://',
        'profile_my_posts' => 'My posts',
        'profile_user_posts' => 'User posts',
        'profile_no_posts' => 'You have not created any posts yet.',
        'profile_no_posts_other' => 'This user has not created any posts yet.',
        'profile_avatar_url' => 'Avatar (URL)',
        'profile_avatar_file' => 'Or upload file',
        'profile_save' => 'Save',
        'post_comments_count' => 'comments',
        'post_about' => 'About post',
        'post_author' => 'Author',
        'post_category' => 'Subreddit',
        'post_published_at' => 'Published',
        'post_likes' => 'Likes',
        'support_title' => 'Support us!',
        'support_text' => 'If you like MonoTalk, please support us!',
        'support_btn' => 'Support',
        'subscribe' => 'Subscribe',
        'unsubscribe' => 'Unsubscribe',
        'sidebar_subs' => 'Subscriptions',
        'search' => 'Search',
        'user_status_online' => '🟢 Online',
        'user_status_recent' => '⚫ Seen recently',
        'user_status_minutes_ago' => '⚫ Seen %d min ago',
        'user_status_hours_ago' => '⚫ Seen %d hr ago',
        'user_status_days_ago' => '⚫ Seen %d day(s) ago',
        'user_status_weeks_ago' => '⚫ Seen %d week(s) ago',
        'user_status_months_ago' => '⚫ Seen %d month(s) ago',
        'user_status_years_ago' => '⚫ Seen %d year(s) ago',
    ],
];

$translations['ru']['create_image_flow_help'] = 'Если хотите получить схему "текст -> картинка -> текст", напишите первую часть текста, оставьте пустую строку, потом продолжите текст. Загруженная картинка встанет между этими блоками.';
$translations['en']['create_image_flow_help'] = 'If you want a "text -> image -> text" layout, write the first part of the text, leave an empty line, then continue the text. The uploaded image will appear between those text blocks.';

function getLang(): string {
    $allowed = ['ru', 'en'];
    if (isset($_GET['lang']) && in_array($_GET['lang'], $allowed, true)) {
        $lang = $_GET['lang'];
        $_SESSION['lang'] = $lang;
        setcookie('lang', $lang, time() + 60 * 60 * 24 * 365, '/');
        return $lang;
    }
    if (isset($_SESSION['lang']) && in_array($_SESSION['lang'], $allowed, true)) {
        return $_SESSION['lang'];
    }
    if (isset($_COOKIE['lang']) && in_array($_COOKIE['lang'], $allowed, true)) {
        $_SESSION['lang'] = $_COOKIE['lang'];
        return $_COOKIE['lang'];
    }
    $_SESSION['lang'] = 'ru';
    return 'ru';
}

function t(string $key): string {
    global $translations;
    $lang = getLang();
    return $translations[$lang][$key] ?? $translations['ru'][$key] ?? $key;
}

function catName(array $cat, string $lang): string {
    $key = $lang === 'en' ? 'name_en' : 'name';
    return $cat[$key] ?? $cat['name'] ?? '';
}
